### ISSUE TITLE
Update the UI of WalletConnect related screens

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1005]
```[tasklist]
### Tasks
- [ ] Use existing `<ConnectionRequestScreen>` with evolution to allow crypto wallet selection
- [ ] https://github.com/verida/vault-mobile/issues/1003
- [ ] Implement new Transaction and/or Sign request screen
- [ ] Implement new screen for the Settings > WalletConnect > DApps
- [ ] Implement new screen for the Settings > WalletConnect > DApp details
- [ ] Deprecate/Remove the old WalletConnect modals
```
