### ISSUE TITLE
Add Sentry capture to Polygon ID feature

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1013]
```[tasklist]
### Tasks
- [x] Add Sentry in the webapp
- [x] Capture exceptions with Sentry (both webapp and React Native app)
- [x] Add Sentry breadcrumbs to add context
```
