### ISSUE TITLE
Configure import paths with a prefix

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1015]
As of `0.4.0`, `ts-config` defines paths for each first-level folder in `src`.

While having paths is great, having to update `ts-config` when the first-level folders change is annoying.

More importantly, most first-level folder export directly their content, meaning they can/should be imported like `import {} from 'config'` or `import {} from 'constants'`. The problem is this conflicts with built-in modules.

We should have a single path defined in `ts-config` to give `src` a prefix, which would solve the two issues described above.

There are two convention for the prefix:
- `@` => `@/config`
- `~` => `~/config`

I (@aurelticot) personally prefer `~` as `@` can be confusing and conflicting with npm package namespaces `@config/...`. Also, as the imports are sorted by name, they would be clearly grouped and isolated from npm packages with namespace `@...`

```[tasklist]
### Tasks
- [x] Agree on the prefix
- [x] Update `ts-config` with the prefix and remove all other paths
- [x] Update the codebase with the prefix
- [ ] If not already configure eslint with absolute paths rule
- [x] Check the impacts on `jest` and the `jest` config
```
