### ISSUE TITLE
[EPIC] Refactor the styles and theme

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1181]
- [ ] Create a theme feature and move related files
  - Organised by contexts, hooks, types, themes
  - `ThemeContext.ts`,  `useThemeAwareStyle.ts`, the content of `styles`, `constants/text.js`
  - The initialisation of the font in `App.tsx`
- [ ] Rework the properties of the theme
  - push more to abstract names (primary, background, etc.) for colours and all and limit the use of literal names (green, blue, etc.)
  - Work with Excited because they need to harmonise in Figma as well
- [ ] Deprecate the pre-defined styles for button, divider, etc.
  - Instead, have a proper `<Component>` with their style for each
- [ ] Have each and every component to use the provided theme for their styling
  - `useThemeAwareStyles` or `useTheme`
