### ISSUE TITLE
[EPIC] Rework the Inbox feature

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1182]
- [ ] Reorganise in an inbox feature
- [ ] Move everything inbox-related
- [ ] Rework how messages are fetched
  - In the background with listener
    - As in, in a Context, but could also research when the app is not in the foreground (kinda works already works with the remote notification from the Notification server and Firebase, but see if we can do without Firebase, do with the PouchDB listener only)
  - Cache the messages
  - Should not need to refetch when displaying the inbox itself
- [ ] Properly handle switching identities
  - Try to keep the cache of the other identities but obviously without mixing it with the each others
- [ ] UI
  - [ ] Inbox itself
  - [ ] Different message types
    - Some requests are already implemented for other protocols
```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/840
- [ ] https://github.com/verida/vault-mobile/issues/1150
- [ ] https://github.com/verida/vault-mobile/issues/1477
- [ ] https://github.com/verida/vault-mobile/pull/1481
- [ ] https://github.com/verida/vault-mobile/issues/813
- [ ] https://github.com/verida/vault-mobile/issues/943
```
