### ISSUE TITLE
[EPIC] Rework the Identity management

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1186]
```[tasklist]
### Tasks
- [ ] Move things in identities feature
- [ ] Migrate from singleton class outside of React to a Context or Redux (thunk)
- [ ] Optimise state management between the context, redux (if needed) the local storage
- [ ] Research to allow multiple accounts connected at the same time (for quick switching during Connection Request for instance)
```
