### ISSUE TITLE
[EPIC] Fixes to display of social / following data

### ISSUE THREAD

**Issue by tahpot** [verida/vault-mobile#1225]
See this video:

https://www.loom.com/share/70157d0eac0c4a5ba7e5cea67062cb7e

```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/1226
- [ ] https://github.com/verida/vault-mobile/issues/1227
- [ ] https://github.com/verida/vault-mobile/issues/1228
- [ ] https://github.com/verida/vault-mobile/issues/1229
```
