### ISSUE TITLE
[EPIC] Fix vulnerabilities from Abdul Rehman

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1231]
```[tasklist]
### Tasks
- [ ] #1230
- [ ] https://github.com/verida/vault-mobile/issues/1232
- [ ] https://github.com/verida/vault-mobile/issues/1233
- [ ] https://github.com/verida/vault-mobile/issues/1234
- [ ] https://github.com/verida/vault-mobile/issues/1235
- [ ] https://github.com/verida/vault-mobile/issues/1281
- [ ] https://github.com/verida/vault-mobile/issues/1282
- [ ] https://github.com/verida/vault-mobile/issues/1283
```
