### ISSUE TITLE
Harmonise Android and iOS apps

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1273]
Make a full review of the apps on Android and iOS and harmonise their name, logo, etc. Both in the codebase and in the stores.
For example, the Internal/staging app on iOS is called "Verida Wallet Internal" in the store (only TestFlight) but when installed it's "VeridaInternal".

We currently have 2 applications on Android and 3 on iOS:
- The internal/staging one, normally called "Verida Wallet Internal"
  - Built when we are finalising the release, from the release branch
  - Spend a few days in TestFlight for final testing
  - TestFlight access is limited to the Verida Team
  - Never hit the store, only used via TestFlight
- The public/external one: "Verida Wallet"
  - The public application
  - Built after successfully testing the new release of the Internal app and the release merged on the main branch
  - As soon as it's built, it's published publicly to the store
  - Has it's own TestFlight but because it's publicly available in the store quickly, TestFlight is useless here
  - There is a relatively long list of users having TestFlight access.
- The dev one
  - Only on iOS.
  - On Android, the dev one is the same as the staging/internal so we can't have both installed

### suggestions
- We need 3 different apps (different app Id), so that we can have them all installed at the same time on a device
  - The external/production/actual app
  - An internal/staging app
    - Used as a "nightly" built from the `develop` branch. We don't have the credit (and the need) to build it nightly, so more of when there's something interesting in the `develop` branch, potentially unstable and/or incomplete though.
    - Not published publicly, stays internal but technically could be open to external users.
    - Find a way to make it available in Android as well, (more easily than having to install the APK
  - A development app
    - Not published to or even referenced in the stores
    - Locally installed on physical device 
    - No conflicts with the 2 others
- We need to harmonise their name
  - Same on Android and iOS
  - Define the naming for the 3 apps
  - Ensure the names are the same in the code and the stores, so there's consistency
- Distinguish the apps by their logo
  - Have a different logo for the 3 apps, so we recognise them easily
- Find a way to distinguish the apps inside the App itself
  - Could be something in the header or at least in the Settings page

```[tasklist]
### Tasks
- [ ] Set up the equivalent of TestFlight for Android for the production app
- [ ] Deploy the internal app on Google play store with limited access to Verida team only
- [ ] Set up auto-deploy to the store in the CI
- [ ] Harmonise their name
- [ ] Distinguish the apps by their logo
- [ ] Distinguish the apps inside the App itself
```

### Process
- Development with the dev app
- Time to time make an internal app build from `develop`
- It becomes available in TestFlight and Google equivalent for preview and testing
- When finalising a release, from the release branch, instead of building the internal, we build the production directly
- It becomes available in TestFlight and Google equivalent for QA and for all authorised external  users (ambassadors, etc.)
- We test it for a few days (and can ask the external users to test as well)
- If we're good with it, we just need to press the "Publish" button, no need to build again because it's already the production build

Note: We would reduce the number of build doing so
