### ISSUE TITLE
[EPIC] Refactor crypto wallet implementation

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1294]
```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/pull/1379
- [ ] https://github.com/verida/vault-mobile/pull/1390
- [ ] https://github.com/verida/vault-mobile/pull/1393
- [ ] https://github.com/verida/vault-mobile/issues/1091
- [ ] https://github.com/verida/vault-mobile/issues/1223
- [ ] https://github.com/verida/vault-mobile/issues/1130
- [ ] https://github.com/verida/vault-mobile/issues/1088
- [ ] https://github.com/verida/vault-mobile/issues/1074
- [ ] https://github.com/verida/vault-mobile/issues/1222
- [ ] https://github.com/verida/vault-mobile/issues/924
- [ ] https://github.com/verida/vault-mobile/issues/1295
```

```[tasklist]
### Lower priority
- [ ] https://github.com/verida/vault-mobile/issues/1224
- [ ] https://github.com/verida/vault-mobile/issues/666
```

```[tasklist]
### Need more thoughts (UX notably)
- [ ] https://github.com/verida/vault-mobile/issues/1089
- [ ] https://github.com/verida/vault-mobile/issues/1090
```
