### ISSUE TITLE
[EPIC] Enhance WalletConnect

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1307]
```[tasklist]
### Tasks
- [ ] #1005
- [ ] https://github.com/verida/vault-mobile/issues/1308
- [ ] https://github.com/verida/vault-mobile/issues/1003
- [ ] https://github.com/verida/vault-mobile/issues/1006
- [ ] https://github.com/verida/vault-mobile/issues/1309
- [ ] https://github.com/verida/vault-mobile/issues/1310
```
