### ISSUE TITLE
[EPIC] Manage Storage Nodes

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#1350]
```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/1351
- [ ] https://github.com/verida/vault-mobile/issues/1352
- [ ] https://github.com/verida/vault-mobile/issues/1353
- [ ] https://github.com/verida/vault-mobile/issues/1354
- [ ] https://github.com/verida/vault-mobile/issues/460
```
