### ISSUE TITLE
Wallet: Production ready using Wallet provider and NEAR support

### ISSUE THREAD

**Issue by saadibrahim** [verida/vault-mobile#418]
- [x] [Finish NEAR support with NEP 141](https://github.com/verida/zenhub/issues/5#issuecomment-1087917386) - (By end of week)
- [x] #421
- [ ] #419 (3-4 days)
- [x] #456
- [x] #254 (hard to estimate, couple of days of research and trying things, perhaps @pranavburnwal can help here)

Infrastructure:
- [x] #489

Missing features:
- [x] #476
- [x] #486
- [ ] #420 (4-5 days)
- [x] #482
- [x] #485
- [x] #483
- [x] #484
- [x] #524
- [ ] #525
- [ ] #526
- [ ] #527
- [ ] #528
- [x] #529
- [x] #546
- [x] #551
- [ ] #547

Others:
- [ ] Wallet:  use typescript on frontend
- [ ]  Wallet: Handle numbers better.. commas and decimals
- [ ]  Wallet: CAIP library throws error often, get rid of it
- [ ] Wallet: Sometimes there's a discrepancy between token balance due to different data sources, one comes from an database based REST API, another comes from Node - mostly seen with Ethereum, Moralis to be blamed.
- [ ] Wallet: Caching
- [ ] Wallet: Better error handling (fail to load balances or prices)

Ethereum Specific Issues:
- [ ] #427
- [ ] #428
- [ ] #429
- [ ] #430

Algorand specific issues:

- [x] #265
- [x] #236

There's quite a few things missing from the designs, some are redundant, some too complex, would have to pick things we want to implement at this stage.
