### ISSUE TITLE
[EPIC] Upgrade WalletConnect to v2

### ISSUE THREAD

**Issue by andy-verida** [verida/vault-mobile#835]
From WalletConnect doc and news:  [Starting from June 29, all wallets and dapps are expected to have migrated to the WalletConnect v2.0 servers. This includes dapps that are using self-hosted WalletConnect v1.0 servers.](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595) 

### As of Verida Wallet 0.3.47

- WalletConnect v1 implemented with support to Ethereum and Algorand
- WalletConnect v2 implemented with support to NEAR
- WalletConnect v2 is using the early stage v2 SDK
- Polygon was not a priority at the time so is not supported at all
- A WalletConnect URI can be passed through Verida Connect

Original design documents:
https://www.notion.so/verida/Tech-Design-WalletConnect-e5a97435cd8d483088c6b49a6f8c1017
https://www.notion.so/verida/Wallet-Connect-Integration-dfc06db0da794a7fa8c714eba6943f8d

```[tasklist]
### Tasks
- [x] Upgrade WalletConnect v2 dependencies
- [x] Rework/refactor WalletConnect v2 implementation (SDK changed quite a lot. Could also clean up and harmonise the patterns, ensure fully typed, etc.)
- [x] Support Ethereum, Polygon and NEAR (could [migrate from v1](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0)?). Check Algorand support
- [x] Ensure the integration with Verida Connect continue to works
- [x] Remove the WalletConnect v1 implementation (when the main dapps are working with v2 or when v1 totally shutdown)
- [x] Tests WalletConnect v2 against the [lab examples](https://lab.web3modal.com) and main dapps (Uniswap, etc.)
- [x] Any way to support Deep Link from Dapps?
- [x] Try to implement in a way we can support new chains easily in the future
```

_Note: This issue is an Epic, convert the tasks above to issues to work on them separately if needed_

### Check and manage previous issues

- [x] #657 
- [x] #658 
- [x] #694 
- [x] #707 
- [x] #447 
- [x] #279
- [x] #655 
- [x] #666 

_Note: Some are relatively old, feel free to close if no longer relevant or already implemented_
