### ISSUE TITLE
[EPIC] Polygon ID

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#889]
```[tasklist]
### Tasks
- [x] #887
- [x] #898
- [x] #908
- [x] #890
- [x] #892
- [ ] https://github.com/verida/vault-mobile/issues/933
- [ ] https://github.com/verida/vault-mobile/issues/990
- [ ] https://github.com/verida/vault-mobile/issues/940
- [ ] https://github.com/verida/vault-mobile/issues/1016
- [ ] https://github.com/verida/vault-mobile/issues/1007
- [ ] https://github.com/verida/vault-mobile/issues/1013
- [ ] https://github.com/verida/vault-mobile/issues/1021
- [ ] #894
- [ ] https://github.com/verida/vault-mobile/issues/1123
- [ ] https://github.com/verida/vault-mobile/issues/1009
- [ ] https://github.com/verida/vault-mobile/issues/1095
- [ ] https://github.com/verida/vault-mobile/issues/1019
- [ ] https://github.com/verida/vault-mobile/issues/1018
- [ ] https://github.com/verida/vault-mobile/issues/1017
- [ ] https://github.com/verida/vault-mobile/issues/1037
- [ ] https://github.com/verida/vault-mobile/issues/1010
- [ ] #888
- [ ] https://github.com/verida/vault-mobile/issues/1011
- [ ] https://github.com/verida/vault-mobile/issues/1022
- [ ] #891
- [ ] #909
- [ ] https://github.com/verida/vault-mobile/issues/1035
- [ ] https://github.com/verida/vault-mobile/issues/1300
- [ ] https://github.com/verida/vault-mobile/issues/1319
- [ ] https://github.com/verida/vault-mobile/issues/1322
- [ ] https://github.com/verida/vault-mobile/issues/1324
- [ ] https://github.com/verida/vault-mobile/issues/1325
- [ ] https://github.com/verida/vault-mobile/issues/1343
- [ ] https://github.com/verida/vault-mobile/issues/1346
- [ ] https://github.com/verida/vault-mobile/issues/1332
```
Order of items above is a mix of priority and easiness

```[tasklist]
### To explore before committing
- [ ] #896
```
