### ISSUE TITLE
[EPIC] Prepare Wallet for mainnet

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#925]
May have to split this EPIC in two tickets:
- One for the absolutely required work for the mainnet support and launch
- One for the subsequent stuff

_Note: turn the items above as issues to work on them separately_

```[tasklist]
### Required at launch
- [ ] https://github.com/verida/vault-mobile/issues/1061
- [ ] https://github.com/verida/vault-mobile/issues/1072
- [ ] https://github.com/verida/vault-mobile/issues/1120
- [ ] https://github.com/verida/vault-mobile/issues/1113
- [ ] https://github.com/verida/vault-mobile/issues/1073
- [ ] https://github.com/verida/vault-mobile/issues/1153
- [ ] https://github.com/verida/vault-mobile/issues/1151
- [ ] https://github.com/verida/vault-mobile/issues/1121
- [ ] https://github.com/verida/vault-mobile/issues/1076
- [x] Fix Polygon ID network to its Mainnet
- [x] Support resolving Cheqd DID
```

```[tasklist]
### Can come after launch?
- [ ] https://github.com/verida/vault-mobile/issues/977
- [ ] https://github.com/verida/vault-mobile/issues/1152
- [ ] https://github.com/verida/vault-mobile/issues/1074
- [ ] Verida One gated access
```
