### ISSUE TITLE
[EPIC] Refactor for optimisation and performance

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#939]
```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/937
- [ ] https://github.com/verida/vault-mobile/issues/938
- [ ] https://github.com/verida/vault-mobile/issues/914
- [ ] https://github.com/verida/vault-mobile/issues/947
- [ ] https://github.com/verida/vault-mobile/issues/902
- [ ] https://github.com/verida/vault-mobile/issues/1067
- [ ] Define and Implement a location to init the application
```
