### ISSUE TITLE
Define and implement a proper logging mechanism throughout the App

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#941]
`console` is supposedly impacting the performances while in Production.
Currently we also have a lint rule banning `console` but we still use it resulting in a lot of linting errors.

We should a proper way to log throughout the App.
What's the best practice in React Native?

```[tasklist]
### Tasks
- [ ] Use a script or lib to remove all `console` during build
- [ ] Set the lint rule to `warn` level
- [ ] Use an advanced logging library?
- [ ] Replace all `console` by the custom logger (if chosen to use a logging lib)
- [ ] Use Sentry.addBreadcrumb when useful, to provide more details in Sentry
```

Additional thoughts:

How about `LogBox`?

Winston cannot be used in React Native:
https://github.com/winstonjs/winston/issues/895

[react-native-logs](https://github.com/onubo/react-native-logs) seems the be name coming often in search results
