### ISSUE TITLE
[EPIC] Navigator and Screen layout refactoring

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#947]
This is an Epic. Scope below can be split. Convert the items of the list into issues to work and follow them separately.

```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/1155
- [ ] https://github.com/verida/vault-mobile/issues/1154
- [ ] https://github.com/verida/vault-mobile/issues/982
- [ ] https://github.com/verida/vault-mobile/issues/52
- [ ] https://github.com/verida/vault-mobile/issues/984
- [ ] https://github.com/verida/vault-mobile/issues/1176
- [ ] https://github.com/verida/vault-mobile/issues/1448
- [ ] https://github.com/verida/vault-mobile/issues/1156
- [ ] https://github.com/verida/vault-mobile/issues/1067
- [ ] https://github.com/verida/vault-mobile/issues/946
- [ ] https://github.com/verida/vault-mobile/issues/1157
- [ ] https://github.com/verida/vault-mobile/issues/985
- [ ] https://github.com/verida/vault-mobile/issues/849
- [ ] https://github.com/verida/vault-mobile/issues/986
```
