### ISSUE TITLE
Optimise the account creation + UI updates

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#950]
The `AccountManager.createAccount` aims at creating a new Verida Account. There are a few steps in this process (at least from a user point of view).
One argument of the function is `updateProgress` which allows giving a feedback on the status of the different steps.
The UI uses this to provide a visual feedback to the user.

Problem is, when an error occurs, the status are not properly updated. Example: "Creating DID" is stuck in processing, while "Creating profile" is in error.
Which is confusing as the creation of the public profile would only start if the DID has been created.

![Simulator Screenshot - iPhone 13 - 2023-06-27 at 17 58 34](https://github.com/verida/vault-mobile/assets/61808169/a8e6b352-a8c4-4f83-8d38-8be42d0608d0)

It is understood that the way the function creates the accounts might be slightly different from what the steps depicted in the UI but this function would benefit from:

```[tasklist]
### Tasks
- [ ] Refactor to ensure the status are updated properly, even in case of error (see note below)
- [ ] Try to capture meaningful error to report to the users in the UI
- [ ] Add a "loading" status for the "StorageLocation" step (doesn't have right now)
```

Note: The `catch` updating only the profile step. It would make sense to split the `try/catch`, one for the DID creation, another one for setting the profile, so it better catch the status.
