### ISSUE TITLE
[EPIC] Strengthen Verifiable Credentials support

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#955]
Supporting Verifiable Credentials is an important feature of the Verida Wallet as it follow some of the principles of Verida, particularly around the self-sovereignty (the user holds its credentials), the privacy, etc.

Another interesting aspect is, by supporting VC Standards, the Wallet can be used with Applications that are not integrated with, or not even aware of the Verida Networks. It opens us to the whole SSI ecosystem (in "competition" with other SSI wallets).

```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/954
- [ ] https://github.com/verida/vault-mobile/issues/956
- [ ] https://github.com/verida/vault-mobile/issues/957
- [ ] https://github.com/verida/vault-mobile/issues/909
- [ ] https://github.com/verida/vault-mobile/issues/958
- [ ] https://github.com/verida/vault-mobile/issues/959
- [ ] https://github.com/verida/vault-mobile/issues/960
- [ ] https://github.com/verida/vault-mobile/issues/961
- [ ] https://github.com/verida/vault-mobile/issues/962
- [ ] https://github.com/verida/vault-mobile/issues/963
- [ ] https://github.com/verida/vault-mobile/issues/889
- [ ] https://github.com/verida/vault-mobile/issues/1320
- [ ] https://github.com/verida/vault-mobile/issues/1321
```
