### ISSUE TITLE
Update the `DIDNonExistentModal` component

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#971]
This modal is shown to the user when an Identity/Account cannot be resolved. The current message says "This identity no longer exists due to a network upgrade and will be removed from your Wallet", which is misleading as it can be a temporary outage.

The message should be less alarming, something like:

"This Identity is not available at the moment. This can be due to a Network or Blockchain issue. Please wait a moment. If you think this Identity don't exist anymore, you can remove it from your Wallet."

```[tasklist]
### Tasks
- [x] Update the message of the dialog, see suggested message above
- [x] Reword the "Delete Identity" button label to "Remove Identity from Wallet"
- [x] Reword the Alert message to "Remove Identity from the Wallet"
- [x] Reword the Alert button label to "Remove" instead of "Delete"
```
