### ISSUE TITLE
Make the whole Wallet configuration overridable via Firebase

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#972]
```[tasklist]
### Tasks
- [x] Refactor codebase to use `config/environment.ts` as the only place to get env variable and export a Config object
- [ ] https://github.com/verida/vault-mobile/issues/1036
- [x] Rename `config/environment.ts` to `config/index.ts`
- [x] Define what can stay hardcoded and what should be configurable
- [x] Define how secrets should be managed
- [x] Question: Can we use environment variables to define the configuration at build and then allow overriding it with Firebase
- [ ] https://github.com/verida/vault-mobile/issues/974
```
