### ISSUE TITLE
[EPIC] Implement updated UI design

### ISSUE THREAD

**Issue by aurelticot** [verida/vault-mobile#981]
```[tasklist]
### Tasks
- [ ] https://github.com/verida/vault-mobile/issues/52
- [ ] https://github.com/verida/vault-mobile/issues/982
- [ ] https://github.com/verida/vault-mobile/issues/984
- [ ] https://github.com/verida/vault-mobile/issues/986
- [ ] https://github.com/verida/vault-mobile/issues/985
- [ ] https://github.com/verida/vault-mobile/issues/849
- [ ] https://github.com/verida/vault-mobile/issues/836
- [ ] https://github.com/verida/vault-mobile/issues/837
- [ ] https://github.com/verida/vault-mobile/issues/1296
- [ ] Update Authentication and PIN/Bio screen
- [ ] Update Loading component throughout the App
- [ ] Add onboarding screens (few screens explaing whast is Verida and the Wallet, at first install)
- [ ] https://github.com/verida/vault-mobile/issues/1140
- [ ] https://github.com/verida/vault-mobile/issues/1141
- [ ] https://github.com/verida/vault-mobile/issues/1122
- [ ] https://github.com/verida/vault-mobile/issues/1161
- [ ] https://github.com/verida/vault-mobile/issues/518
- [ ] Update Data list screen
- [ ] Update Data item screen
- [ ] https://github.com/verida/vault-mobile/issues/954
- [ ] https://github.com/verida/vault-mobile/issues/959
- [ ] https://github.com/verida/vault-mobile/issues/769
- [ ] https://github.com/verida/vault-mobile/issues/1168
- [ ] https://github.com/verida/vault-mobile/issues/1133
- [ ] https://github.com/verida/vault-mobile/issues/1299
- [ ] Use new Connection screen for all protocol connections (Verida Connect, WalletConnect, etc.)
- [ ] https://github.com/verida/vault-mobile/issues/987
- [ ] Implement new Request screen design
- [ ] https://github.com/verida/vault-mobile/issues/1297
- [ ] https://github.com/verida/vault-mobile/issues/1298
```
